//! SVG element factory functions.
//!
//! Provides factory functions for SVG elements (e.g. `path`, `rect`, `circle`).
//! All functions return [`XmlElement`](crate::XmlElement), which self-closes
//! when children are empty.
//!
//! This module is enabled by the `svg` feature (default on).

use crate::define_xml_elements;

define_xml_elements! {
    g => "g",
    defs => "defs",
    symbol => "symbol",
    r#use => "use",
    path => "path",
    rect => "rect",
    circle => "circle",
    ellipse => "ellipse",
    line => "line",
    polyline => "polyline",
    polygon => "polygon",
    svg_text => "text",
    tspan => "tspan",
    text_path => "textPath",
    image => "image",
    clip_path => "clipPath",
    mask => "mask",
    marker => "marker",
    pattern => "pattern",
    filter => "filter",
    linear_gradient => "linearGradient",
    radial_gradient => "radialGradient",
    stop => "stop",
    animate => "animate",
    animate_transform => "animateTransform",
    foreign_object => "foreignObject",
    title => "title",
    desc => "desc",
    fe => "fe",
    fe_blend => "feBlend",
    fe_color_matrix => "feColorMatrix",
    fe_composite => "feComposite",
    fe_flood => "feFlood",
    fe_gaussian_blur => "feGaussianBlur",
    fe_merge => "feMerge",
    fe_merge_node => "feMergeNode",
    fe_offset => "feOffset",
    fe_turbulence => "feTurbulence",
    a => "a",
    animate_motion => "animateMotion",
    fe_component_transfer => "feComponentTransfer",
    fe_convolve_matrix => "feConvolveMatrix",
    fe_diffuse_lighting => "feDiffuseLighting",
    fe_displacement_map => "feDisplacementMap",
    fe_distant_light => "feDistantLight",
    fe_drop_shadow => "feDropShadow",
    fe_func_a => "feFuncA",
    fe_func_b => "feFuncB",
    fe_func_g => "feFuncG",
    fe_func_r => "feFuncR",
    fe_image => "feImage",
    fe_morphology => "feMorphology",
    fe_point_light => "fePointLight",
    fe_specular_lighting => "feSpecularLighting",
    fe_spot_light => "feSpotLight",
    fe_tile => "feTile",
    metadata => "metadata",
    mpath => "mpath",
    script => "script",
    set => "set",
    style => "style",
    svg => "svg",
    switch => "switch",
    view => "view",
}
